accent = "#2a6f88"
cursor = "#fbf1c7"
foreground = "#fbf1c7"
background = "#002b36"
selection_foreground = "#002b36"
selection_background = "#fbf1c7"

color0 = "#073642"
color1 = "#e76f51"
color2 = "#2a9d8f"
color3 = "#e9c46a"
color4 = "#2a6f88"
color5 = "#f4a261"
color6 = "#2a9d8f"
color7 = "#fbf1c7"
color8 = "#586e75"
color9 = "#ef8a73"
color10 = "#3bcba5"
color11 = "#f0d38e"
color12 = "#4a8dad"
color13 = "#f7b981"
color14 = "#3bcba5"
color15 = "#fdf6e3"
